export const GAME_TEXT = {
  TITLE: "Xếp Khối",
  SUBTITLE: "BỘ LẠC ĐẬU PHỘNG",
  INSTRUCTION: "Kéo khối vào bảng, lấp đầy hàng hoặc cột để dọn ô",
  GAME_OVER_TITLE: "Hết chỗ rồi!",
  RESULT: "Kết quả:",
  POINTS: "điểm",
  BTN_PLAY_AGAIN: "Chơi lại",
  BTN_AD_REPLAY: "Xem mock ads để chơi lại",
  BTN_AD_LOADING: "Đang xem mock ads...",
  BTN_AD_CLEARING: "Đang dọn bảng...",
  AD_REPLAY_LABEL: "Mock ads",
  AD_REPLAY_HINT: "Xem mock ads ngắn để dọn toàn bộ bảng và bắt đầu ván mới.",
  BTN_LEADERBOARD: "Bảng điểm",
  LEADERBOARD_TITLE: "Bảng Điểm",
  BTN_CLOSE: "Đóng",
  STAT_BEST: "Tốt nhất",
  STAT_LAST: "Lần trước",
  STAT_TOTAL: "Tổng ván",
  STAT_COMBO: "Combo cao",
  RECENT_HISTORY: "LỊCH SỬ GẦN ĐÂY",
  NO_GAMES: "Chưa có ván nào",
  TOOLTIP_LEADERBOARD: "Bảng điểm",
  TOOLTIP_SOUND_ON: "Tắt âm thanh",
  TOOLTIP_SOUND_OFF: "Bật âm thanh",
  TOOLTIP_PLAY_AGAIN: "Chơi lại",
};
