export const GAME_TEXT = {
  TITLE: "Xếp Khối",
  SUBTITLE: "BỘ LẠC ĐẬU PHỘNG",
  INSTRUCTION: "Kéo khối vào bảng, lấp đầy hàng hoặc cột để dọn ô",
  GAME_OVER_TITLE: "Hết chỗ rồi!",
  RESULT: "Kết quả:",
  POINTS: "điểm",
  BTN_PLAY_AGAIN: "Chơi lại",
  BTN_AD_REPLAY: "Xem quảng cáo để hồi sinh",
  BTN_AD_LOADING: "Đang mở quảng cáo...",
  BTN_AD_CLEARING: "Đang đổi khối...",
  AD_REPLAY_LABEL: "Quảng cáo thưởng",
  AD_REPLAY_HINT: "Xem quảng cáo để đổi sang 3 khối cứu hộ và giữ nguyên bàn.",
  BTN_LEADERBOARD: "Bảng điểm",
  LEADERBOARD_TITLE: "Bảng Điểm",
  BTN_CLOSE: "Đóng",
  STAT_BEST: "Tốt nhất",
  STAT_LAST: "Lần trước",
  STAT_TOTAL: "Tổng ván",
  STAT_COMBO: "Combo cao",
  RECENT_HISTORY: "LỊCH SỬ GẦN ĐÂY",
  NO_GAMES: "Chưa có ván nào",
  TOOLTIP_LEADERBOARD: "Bảng điểm",
  TOOLTIP_SOUND_ON: "Tắt âm thanh",
  TOOLTIP_SOUND_OFF: "Bật âm thanh",
  TOOLTIP_PLAY_AGAIN: "Chơi lại",
};
